### ISSUE TITLE
Functionality of AutoFPS

### ISSUE THREAD

**Issue by MikeSierra-AUT** [kayjay1c6b/MSFS2024_AutoFPS-by-kayJay_1c6#15]
Hi.
I'm new to AutoFPS, so please forgive me if I ask for a commonly known issue
My 'problem' is that MSfs2024_AutoFPS is not linking to MSFS2020 - though I thought I'd understand that it should do so.
With MSFS2024 I notice the linking to MSFS2024, as the Connection Status marks the "MSFS" item in green (which remains red with MSFS2020). Nevertheless in MSFS2024 I don't notice an improvement of FPS - maybe I'm doing something wrong?

Michael.

**Comment by kayjay1c6b** [comment]
This app work only with MSFS 2024. The aim is not to  particularly get more
FPS but rather to avoid stutters and fps drops in certain conditions. So if
you don't see any difference try to dial up some settings because you
probably have some overhead.

wt., 31 gru 2024, 11:11 użytkownik MikeSierra-AUT ***@***.***>
napisał:

**Comment by MikeSierra-AUT** [comment]
Ah! Thank you for your quick response and clarification!
